
# https://github.com/GoogleCloudPlatform/python-docs-samples/blob/5970e991091034cd0c71654476230b035d32f19d/appengine/standard_python3/building-an-app/building-an-app-1/app.yaml
# runtime: python311
# service: abcd

# entrypoint: gunicorn -b :$PORT main:gunicorn_app



runtime: python
service: defaultflex

env: flex
entrypoint: gunicorn -b :$PORT main:gunicorn_app

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# runtime: python39
# service: aistdlimited
# instance_class: F4_1G
# automatic_scaling:
#     min_instances: 1
#     max_instances: 1

# handlers:
# - url: .*
#   script: auto

# entrypoint: gunicorn --timeout 600 -b :$PORT main:app